// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPRK.Backend.Data;

#nullable disable

namespace SPRK.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214112445_AddRoomTableAndSeed")]
    partial class AddRoomTableAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPRK.Backend.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 90,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 43, 589, DateTimeKind.Utc).AddTicks(2624),
                            Description = "Lengkap dengan proyektor dan sound system",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung D3, HH 101",
                            Name = "Ruang D3 Teater"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 90,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 43, 589, DateTimeKind.Utc).AddTicks(3024),
                            Description = "Lengkap dengan proyektor, sound system, dan kursi empuk",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung Pascasarjana, Lantai 6",
                            Name = "Ruang D4 Theater"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 600,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 43, 589, DateTimeKind.Utc).AddTicks(3026),
                            Description = "Layar, Sound system, dan Ruangan super besar",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung Pascasarjana, Lantai 6",
                            Name = "Auditorium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
