// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPRK.Backend.Data;

#nullable disable

namespace SPRK.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217063120_SeedBookings")]
    partial class SeedBookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPRK.Backend.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowerName = "Andi Setiawan",
                            CreatedAt = new DateTime(2026, 2, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 18, 4, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Seminar internal",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 18, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            BorrowerName = "Rina Kurnia",
                            CreatedAt = new DateTime(2026, 2, 14, 12, 30, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Pelatihan lab",
                            RoomId = 2,
                            StartTime = new DateTime(2026, 2, 19, 6, 30, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            BorrowerName = "Dosen TI",
                            CreatedAt = new DateTime(2026, 2, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 20, 3, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Kuliah umum",
                            RoomId = 3,
                            StartTime = new DateTime(2026, 2, 20, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            BorrowerName = "Mahasiswa TI",
                            CreatedAt = new DateTime(2026, 2, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 2, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Diskusi tugas akhir",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        });
                });

            modelBuilder.Entity("SPRK.Backend.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 90,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 0, 0, DateTimeKind.Utc),
                            Description = "Lengkap dengan proyektor dan sound system",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung D3, HH 101",
                            Name = "Ruang D3 Teater"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 90,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 0, 0, DateTimeKind.Utc),
                            Description = "Lengkap dengan proyektor, sound system, dan kursi empuk",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung Pascasarjana, Lantai 6",
                            Name = "Ruang Theater Pascasarjana"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 600,
                            CreatedAt = new DateTime(2026, 2, 14, 11, 24, 0, 0, DateTimeKind.Utc),
                            Description = "Layar, Sound system, dan Ruangan super besar",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung Pascasarjana, Lantai 6",
                            Name = "Auditorium"
                        });
                });

            modelBuilder.Entity("SPRK.Backend.Entities.Booking", b =>
                {
                    b.HasOne("SPRK.Backend.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
